Add app required models
cedricbahirwe/dialer-android pull request #21
Opened 2023-01-24 13:05 UTC by cedricbahirwe

2023-01-24 15:45 UTC, esthcarelle reviewed
Why having a companion object inside a data class model?

2023-01-24 15:46 UTC, cedricbahirwe commented
> Why having a companion object inside a data class model?

Please, Which File exactly?

2023-01-24 15:47 UTC, esthcarelle requested changes
Can we have the strings not hardcoded sil te plait?

2023-01-24 15:50 UTC, cedricbahirwe commented
> Can we have the strings not hardcoded sil te plait?

Please mention the file, or add a comment from the file directly so I can see it

2023-01-24 15:51 UTC, esthcarelle requested changes

2023-01-24 15:51 UTC, esthcarelle commented on TheDialer/app/src/main/java/com/cedricbahirwe/dialer/model/Contact.kt
> +    companion object {
why having a companion object inside a data class model?

2023-01-24 15:53 UTC, cedricbahirwe commented on TheDialer/app/src/main/java/com/cedricbahirwe/dialer/model/Contact.kt
> +    companion object {
I have replied in the above comment, Does it make sense or Am I Missing something?

2023-01-24 16:03 UTC, esthcarelle commented on TheDialer/app/src/main/java/com/cedricbahirwe/dialer/model/Contact.kt
> +    companion object {
ooh okay then I think it s better when it is a separate class that has all examples

2023-01-24 21:08 UTC, cedricbahirwe commented on TheDialer/app/src/main/java/com/cedricbahirwe/dialer/model/Contact.kt
> +    companion object {
I have resolved this

2023-01-24 21:08 UTC, cedricbahirwe commented on TheDialer/app/src/main/java/com/cedricbahirwe/dialer/model/Contact.kt
> +    companion object {
I have resolved this

2023-01-25 08:15 UTC, esthcarelle approved these changes

2023-01-25 08:25 UTC, merged