Splash Screen
cedricbahirwe/dialer-android pull request #42
Opened 2023-10-06 15:30 UTC by esthcarelle

### Quick Description of What this is about

!! It's not yet ready to be reviewed, I want first to make sure this is what you want
PS: WIll upload Dark vs Light mode later
[device-2023-10-06-172542.webm](https://github.com/cedricbahirwe/dialer-android/assets/52702726/0d12d4e1-1567-43c1-9210-32fbf415ec95)

2023-10-06 16:33 UTC, cedricbahirwe commented
> ### Quick Description of What this is about
> !! It's not yet ready to be reviewed, I want first to make sure this is what you want PS: WIll upload Dark vs Light mode later [device-2023-10-06-172542.webm](https://github.com/cedricbahirwe/dialer-android/assets/52702726/0d12d4e1-1567-43c1-9210-32fbf415ec95)

That's totally it

2023-10-09 13:02 UTC, esthcarelle commented
@cedricbahirwe do you have any idea why I Can't upload files?

2023-10-09 13:07 UTC, esthcarelle commented
Second video recording(light Mode and Android 13)
[device-2023-10-09-144205.webm](https://github.com/cedricbahirwe/dialer-android/assets/52702726/2dcd4add-8b68-4cf1-8b78-b3aab9083f40)

2023-10-09 13:22 UTC, cedricbahirwe commented
> @cedricbahirwe do you have any idea why I Can't upload files?

Yes You can

2023-10-09 13:24 UTC, cedricbahirwe commented
> ### Quick Description of What this is about
> This PR is all about the splash screen
> 
> * I have added the splash api and handled android versions below and above 12 separately(Videos recording shows both of them)
> * For the dark and light mode I have added a colors(night mode) file that will be handling colors in dark mode
> * The sizes are not yet perfect so I need you to generate another png file that matches the size want
> * I also need a brand name png that has a transparent background(The one you gave me has a white background)
> 

The icon I provided, did not have any background color

2023-10-09 13:26 UTC, cedricbahirwe commented
> * I have added the splash api and handled android versions below and above 12 separately(Videos recording shows both of them)
> * For the dark and light mode I have added a colors(night mode) file that will be handling colors in dark mode 

Apart from the dark mode background, this looks awesome

2023-10-09 13:29 UTC, cedricbahirwe commented
![273172129-99057114-0820-4507-b7ec-75f7a8ddc3f9](https://github.com/cedricbahirwe/dialer-android/assets/49038614/d8fb9208-75c2-4194-ac15-45791e79524f)
This one is perfect because it works in both dark and light mode,
What do you think, and it does not have any colored background (dimensions: 200x80)

2023-10-09 13:32 UTC, cedricbahirwe requested changes

2023-10-09 13:32 UTC, cedricbahirwe commented on TheDialer/app/src/main/res/drawable/branding_name.png
This is the wrong brand icon with the background (My bad if this is what I provided)
Here you go:
![273172129-99057114-0820-4507-b7ec-75f7a8ddc3f9](https://github.com/cedricbahirwe/dialer-android/assets/49038614/1167ceb3-fa90-4c14-847a-c1605eabd4c4)

2023-10-09 13:33 UTC, cedricbahirwe commented on README.md
Was there a change you needed to make in the README.md file?

2023-10-09 13:35 UTC, esthcarelle commented on README.md
@cedricbahirwe Identation was causing red errors with my android studio but you can check there is no difference with what you had

2023-10-09 13:35 UTC, esthcarelle commented on TheDialer/app/src/main/res/drawable/branding_name.png
okay thanks

2023-10-09 13:38 UTC, cedricbahirwe commented on TheDialer/app/src/main/res/drawable/branding_name.png
Does this work?

2023-10-09 13:53 UTC, esthcarelle commented on TheDialer/app/src/main/res/drawable/branding_name.png
yes

2023-10-10 10:18 UTC, esthcarelle commented on TheDialer/app/src/main/res/drawable/branding_name.png
yeah

2023-10-10 10:19 UTC, esthcarelle commented on TheDialer/app/src/main/res/drawable/branding_name.png
@cedricbahirwe 
https://github.com/cedricbahirwe/dialer-android/assets/52702726/06c6d7f6-9280-4623-a213-21b833b765d4


https://github.com/cedricbahirwe/dialer-android/assets/52702726/d15e4bc9-01f5-435d-9eee-19eb5cc60bd2

2023-10-10 10:29 UTC, cedricbahirwe commented on TheDialer/app/src/main/res/drawable/branding_name.png
LGTM, let's launch🚀

2023-10-10 10:30 UTC, cedricbahirwe approved these changes

2023-10-10 10:32 UTC, esthcarelle commented
@cedricbahirwe can you first run it on your testing phone to check the drawable sizes(icons)?since we only added one icon it might cause responsiveness issues

2023-10-10 10:39 UTC, cedricbahirwe commented
> @cedricbahirwe can you first run it on your testing phone to check the drawable sizes(icons)? since we only added one icon it might cause responsiveness issues

Let me do that

2023-10-10 10:43 UTC, cedricbahirwe commented
Looks like the code is not pushed yet

2023-10-10 10:43 UTC, cedricbahirwe commented
I'm getting the white background

2023-10-10 10:45 UTC, esthcarelle commented
@cedricbahirwe My Bad!You can check now, it was not pushed

2023-10-10 10:58 UTC, cedricbahirwe commented
Now, it's working well
https://github.com/cedricbahirwe/dialer-android/assets/49038614/a71dab13-7476-4e61-b236-e06b454074c0

2023-10-10 10:59 UTC, merged